### ISSUE TITLE
Audio plays consistent tone when page is navigated away from

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/A-Web-Packets-Journey#1]
When the game is running on a browser tab and the browser app is sent to the background (via replacement by another app, navigation to the home screen, or even locking the phone and turning the screen off) the game is silent for 1-2 seconds before outputting a consistent tone. The tone seems to vary dependent on the audio that is playing the instant the app is background. The consistent tone may be a loop of whatever is in the sound buffer at the time the app is background.

Tested on Android 7 using Firefox Focus.

**Comment by nbriz** [comment]
yea, i've noticed this on iOS too
