### ISSUE TITLE
Make title image non-draggable.

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/A-Web-Packets-Journey#2]
You can't see my mouse in this screenshot but you should be able to see the image dragging behavior without it if you look closely.

![screenshot from 2018-09-28 09-50-45](https://user-images.githubusercontent.com/3193533/46233627-6172bc80-c341-11e8-97f3-1c94540c5430.png)

This is a quick fix I believe, by either setting user drag events in the image css to none or `pointer-events: none`. More info [here](https://stackoverflow.com/questions/12906789/preventing-an-image-from-being-draggable-or-selectable-without-using-js#12906840).

**Comment by nbriz** [comment]
ah yea, good catch!
